### PR TITLE
Update for latest Swift (1.2)

### PR DESCRIPTION
**Pull request by Jamonek**
Update parts of the code to support Swift 1.2

I'm not sure how to omit my edits from a pull request.. still a little new to GitHub sadly..

### CODE REVIEW

**Comment by Jamonek** [comment]
Any update

**Comment by octplane** [comment]
Yep, No. Sorry, was away for business. Looking at it verrry soon

**Comment by octplane** [comment]
I have taken your changes to update master @047b301 . Thanks for your PR !

**Comment by Jamonek** [comment]
Thank you! Great work by the way, love the project.

**Pull request closed without merging**
